---
AllCops:
  Enabled: true

Lint/ShadowingOuterLocalVar:
  Enabled: true

Lint/LiteralsInCondition:
  Enabled: true

Lint/NotNilCheck:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedArgument:
  Enabled: true

Style/FavorUnlessOverNegatedIf:
  Enabled: true

Style/FavorUntilOverNegatedWhile:
  Enabled: true

Style/NilCheck:
  Enabled: true

Style/PercentXLiteral:
  Enabled: true

Style/RedundantBegin:
  Enabled: true

Style/RedundantReturn:
  Enabled: true

Style/RedundantSelf:
  Enabled: true

Style/VerboseBlock:
  Enabled: true

Style/PreferNilEmpty:
  Enabled: true

Style/StringLiterals:
  Enabled: true

Metrics/CyclomaticComplexity:
  MaxComplexity: 10

Metrics/MethodLength:
  MaxLength: 40

Metrics/ClassLength:
  MaxLength: 150

Naming/TypeNames:
  Enabled: true
