indent = 4
margin = 120
always_use_return = true
remove_extra_newlines = true
import_to_using = true
pipe_to_function_call = false
short_to_long_function_def = false
long_to_short_function_def = false
whitespace_ops_in_indices = true
normalize_line_endings = "unix"
always_for_in = true
trailing_comma = true
trailing_zero = true
join_lines_based_on_source = true
separate_kwargs_with_semicolon = false
surround_whereblock_typeannotation = false
