---
# cmake-format configuration
# https://cmake-format.readthedocs.io/

format:
  line_width: 120
  tab_size: 2
  use_tabchars: false
  max_prefix_chars: 32
  max_lines_hwrap: 2
  min_prefix_chars: 4
  emit_byteorder_mark: false
  command_case: canonical
  keyword_case: upper
  dangle_parens: false
  dangle_align: prefix

lint:
  public_var_unset_pattern: '^[A-Z][0-9A-Z_]+'
  internal_var_pattern: '^_?[a-z][a-z0-9_]+'
  local_var_pattern: '^[a-z][a-z0-9_]+'
  private_var_pattern: '^_[a-z][a-z0-9_]+'
  function_pattern: '^[a-z][a-z0-9_]+'
  macro_pattern: '^[a-z][a-z0-9_]+'
  max_statement_spacing: 2
  min_statement_spacing: 1
  max_returns: 3
  max_branches: 10
  max_arguments: 5
  max_localvars: 15
  max_statements: 40

markup:
  bullet_char: '*'
  enum_char: .
  first_comment_is_literal: false
