---
# GitHub Licensed configuration
# https://github.com/github/licensed

sources:
  bundler: true
  npm: true
  pip: true
  go: true
  gradle: true
  maven: true
  nuget: true

allowed:
  - mit
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
  - cc0-1.0
  - cc-by-4.0
  - unlicense
  - 0bsd
  - wtfpl
  - python-2.0
  - psf-2.0
  - artistic-2.0
