[tool.robocop]
configure = [
  "line-too-long:line_limit:120",
  "too-many-arguments:max_args:5",
  "too-long-keyword:max_len:40",
  "too-long-test-case:max_len:20",
  "too-many-calls-in-keyword:max_calls:5",
  "too-many-calls-in-test-case:max_calls:8",
]
exclude = []
filetypes = [".robot", ".resource"]
