---
include_checks:
  - W
  - E

ignore_checks:
  - W3002
  - W3010

regions:
  - us-east-1
  - us-west-2
  - eu-west-1
  - ap-southeast-1

format: parseable

templates:
  - cloudformation/**/*.yml
  - cloudformation/**/*.yaml
  - cloudformation/**/*.json
  - infrastructure/**/*.yml
  - infrastructure/**/*.yaml
  - infrastructure/**/*.json
  - cfn/**/*.yml
  - cfn/**/*.yaml
